; STUMP LED Matrix Code - Unoptimized Mode
; Generated by STUMP LED Matrix Code Generator
;
; Register Assignments
; R2 = Pixel address register
; R3 = Color value register
; R1 = Data table pointer

; ORG 0x0000    ; Suggested origin for code section

DATA_TABLE
DEFW 0xFF00    ; [R1, #0] Row 0 base
DEFW 0xFF08    ; [R1, #1] Row 1 base
DEFW 0xFF10    ; [R1, #2] Row 2 base
DEFW 0xFF18    ; [R1, #3] Row 3 base
DEFW 0xFF20    ; [R1, #4] Row 4 base
DEFW 0xFF28    ; [R1, #5] Row 5 base
DEFW 0xFF30    ; [R1, #6] Row 6 base
DEFW 0xFF38    ; [R1, #7] Row 7 base

MAIN_CODE
LD R1, [R7, #0]    ; Load DATA_TABLE address (PC-relative, PC already incremented)
DEFW DATA_TABLE

; --- Pixel (0,0) = White (0x00FF) ---
LD R2, [R1, #0]    ; Get row 0 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x00FF    ; Color data
ST R3, [R2, #0]    ; Store color at (0,0)

; --- Pixel (0,1) = White (0x00FF) ---
LD R2, [R1, #0]    ; Get row 0 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x00FF    ; Color data
ST R3, [R2, #1]    ; Store color at (0,1)

; --- Pixel (0,6) = White (0x00FF) ---
LD R2, [R1, #0]    ; Get row 0 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x00FF    ; Color data
ST R3, [R2, #6]    ; Store color at (0,6)

; --- Pixel (0,7) = White (0x00FF) ---
LD R2, [R1, #0]    ; Get row 0 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x00FF    ; Color data
ST R3, [R2, #7]    ; Store color at (0,7)

; --- Pixel (1,1) = Green (0x001C) ---
LD R2, [R1, #1]    ; Get row 1 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #1]    ; Store color at (1,1)

; --- Pixel (1,2) = Green (0x001C) ---
LD R2, [R1, #1]    ; Get row 1 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #2]    ; Store color at (1,2)

; --- Pixel (1,5) = Green (0x001C) ---
LD R2, [R1, #1]    ; Get row 1 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #5]    ; Store color at (1,5)

; --- Pixel (1,6) = Green (0x001C) ---
LD R2, [R1, #1]    ; Get row 1 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #6]    ; Store color at (1,6)

; --- Pixel (2,1) = Green (0x001C) ---
LD R2, [R1, #2]    ; Get row 2 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #1]    ; Store color at (2,1)

; --- Pixel (2,2) = Green (0x001C) ---
LD R2, [R1, #2]    ; Get row 2 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #2]    ; Store color at (2,2)

; --- Pixel (2,5) = Green (0x001C) ---
LD R2, [R1, #2]    ; Get row 2 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #5]    ; Store color at (2,5)

; --- Pixel (2,6) = Green (0x001C) ---
LD R2, [R1, #2]    ; Get row 2 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #6]    ; Store color at (2,6)

; --- Pixel (4,0) = Green (0x001C) ---
LD R2, [R1, #4]    ; Get row 4 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #0]    ; Store color at (4,0)

; --- Pixel (4,1) = Green (0x001C) ---
LD R2, [R1, #4]    ; Get row 4 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #1]    ; Store color at (4,1)

; --- Pixel (4,2) = Green (0x001C) ---
LD R2, [R1, #4]    ; Get row 4 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #2]    ; Store color at (4,2)

; --- Pixel (4,3) = Green (0x001C) ---
LD R2, [R1, #4]    ; Get row 4 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #3]    ; Store color at (4,3)

; --- Pixel (4,4) = Green (0x001C) ---
LD R2, [R1, #4]    ; Get row 4 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #4]    ; Store color at (4,4)

; --- Pixel (4,5) = Green (0x001C) ---
LD R2, [R1, #4]    ; Get row 4 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #5]    ; Store color at (4,5)

; --- Pixel (4,6) = Green (0x001C) ---
LD R2, [R1, #4]    ; Get row 4 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #6]    ; Store color at (4,6)

; --- Pixel (4,7) = Green (0x001C) ---
LD R2, [R1, #4]    ; Get row 4 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #7]    ; Store color at (4,7)

; --- Pixel (5,0) = Blue (0x0003) ---
LD R2, [R1, #5]    ; Get row 5 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x0003    ; Color data
ST R3, [R2, #0]    ; Store color at (5,0)

; --- Pixel (5,1) = Green (0x001C) ---
LD R2, [R1, #5]    ; Get row 5 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #1]    ; Store color at (5,1)

; --- Pixel (5,2) = Yellow (0x00FC) ---
LD R2, [R1, #5]    ; Get row 5 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x00FC    ; Color data
ST R3, [R2, #2]    ; Store color at (5,2)

; --- Pixel (5,3) = Yellow (0x00FC) ---
LD R2, [R1, #5]    ; Get row 5 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x00FC    ; Color data
ST R3, [R2, #3]    ; Store color at (5,3)

; --- Pixel (5,4) = Yellow (0x00FC) ---
LD R2, [R1, #5]    ; Get row 5 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x00FC    ; Color data
ST R3, [R2, #4]    ; Store color at (5,4)

; --- Pixel (5,5) = Yellow (0x00FC) ---
LD R2, [R1, #5]    ; Get row 5 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x00FC    ; Color data
ST R3, [R2, #5]    ; Store color at (5,5)

; --- Pixel (5,6) = Green (0x001C) ---
LD R2, [R1, #5]    ; Get row 5 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #6]    ; Store color at (5,6)

; --- Pixel (5,7) = Blue (0x0003) ---
LD R2, [R1, #5]    ; Get row 5 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x0003    ; Color data
ST R3, [R2, #7]    ; Store color at (5,7)

; --- Pixel (6,0) = Blue (0x0003) ---
LD R2, [R1, #6]    ; Get row 6 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x0003    ; Color data
ST R3, [R2, #0]    ; Store color at (6,0)

; --- Pixel (6,1) = Red (0x00E0) ---
LD R2, [R1, #6]    ; Get row 6 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x00E0    ; Color data
ST R3, [R2, #1]    ; Store color at (6,1)

; --- Pixel (6,2) = Green (0x001C) ---
LD R2, [R1, #6]    ; Get row 6 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #2]    ; Store color at (6,2)

; --- Pixel (6,3) = Yellow (0x00FC) ---
LD R2, [R1, #6]    ; Get row 6 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x00FC    ; Color data
ST R3, [R2, #3]    ; Store color at (6,3)

; --- Pixel (6,4) = Yellow (0x00FC) ---
LD R2, [R1, #6]    ; Get row 6 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x00FC    ; Color data
ST R3, [R2, #4]    ; Store color at (6,4)

; --- Pixel (6,5) = Green (0x001C) ---
LD R2, [R1, #6]    ; Get row 6 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #5]    ; Store color at (6,5)

; --- Pixel (6,6) = Red (0x00E0) ---
LD R2, [R1, #6]    ; Get row 6 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x00E0    ; Color data
ST R3, [R2, #6]    ; Store color at (6,6)

; --- Pixel (6,7) = Blue (0x0003) ---
LD R2, [R1, #6]    ; Get row 6 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x0003    ; Color data
ST R3, [R2, #7]    ; Store color at (6,7)

; --- Pixel (7,0) = Blue (0x0003) ---
LD R2, [R1, #7]    ; Get row 7 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x0003    ; Color data
ST R3, [R2, #0]    ; Store color at (7,0)

; --- Pixel (7,1) = Blue (0x0003) ---
LD R2, [R1, #7]    ; Get row 7 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x0003    ; Color data
ST R3, [R2, #1]    ; Store color at (7,1)

; --- Pixel (7,2) = Blue (0x0003) ---
LD R2, [R1, #7]    ; Get row 7 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x0003    ; Color data
ST R3, [R2, #2]    ; Store color at (7,2)

; --- Pixel (7,3) = Green (0x001C) ---
LD R2, [R1, #7]    ; Get row 7 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #3]    ; Store color at (7,3)

; --- Pixel (7,4) = Green (0x001C) ---
LD R2, [R1, #7]    ; Get row 7 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x001C    ; Color data
ST R3, [R2, #4]    ; Store color at (7,4)

; --- Pixel (7,5) = Blue (0x0003) ---
LD R2, [R1, #7]    ; Get row 7 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x0003    ; Color data
ST R3, [R2, #5]    ; Store color at (7,5)

; --- Pixel (7,6) = Blue (0x0003) ---
LD R2, [R1, #7]    ; Get row 7 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x0003    ; Color data
ST R3, [R2, #6]    ; Store color at (7,6)

; --- Pixel (7,7) = Blue (0x0003) ---
LD R2, [R1, #7]    ; Get row 7 base address
LD R3, [R7, #0]    ; Load color (PC-relative, PC already incremented)
DEFW 0x0003    ; Color data
ST R3, [R2, #7]    ; Store color at (7,7)

END_PROGRAM
B END_PROGRAM    ; Infinite loop