; STUMP LED Matrix Code - Optimized Mode
; Generated by STUMP LED Matrix Code Generator
;
; Register Assignments
; R6 = Pixel address register
; R5 = Color value register
; R4 = Data table pointer

; ORG 0x0000    ; Suggested origin for code section

DATA_TABLE
DATA 0xFF00    ; [R4, #0] Row 0 base
DATA 0xFF08    ; [R4, #1] Row 1 base
DATA 0xFF10    ; [R4, #2] Row 2 base
DATA 0xFF18    ; [R4, #3] Row 3 base
DATA 0xFF20    ; [R4, #4] Row 4 base
DATA 0xFF28    ; [R4, #5] Row 5 base
DATA 0xFF30    ; [R4, #6] Row 6 base
DATA 0xFF38    ; [R4, #7] Row 7 base
DATA 0x0000    ; [R4, #8] Black
DATA 0x00F2    ; [R4, #9] Red-ish
DATA 0x00F6    ; [R4, #10] Yellow-ish
DATA 0x00FF    ; [R4, #11] White

MAIN_CODE
LD R4, [R7, #0]    ; Load DATA_TABLE address (PC-relative, PC already incremented)
DATA DATA_TABLE

; --- Black (0x0000) - 2 pixels ---
LD R5, [R4, #8]    ; Load color value
LD R6, [R4, #3]    ; Get row 3 base address
ST R5, [R6, #1]    ; Store color at (3,1)
LD R6, [R4, #3]    ; Get row 3 base address
ST R5, [R6, #6]    ; Store color at (3,6)

; --- Red-ish (0x00F2) - 4 pixels ---
LD R5, [R4, #9]    ; Load color value
LD R6, [R4, #5]    ; Get row 5 base address
ST R5, [R6, #3]    ; Store color at (5,3)
LD R6, [R4, #5]    ; Get row 5 base address
ST R5, [R6, #4]    ; Store color at (5,4)
LD R6, [R4, #6]    ; Get row 6 base address
ST R5, [R6, #3]    ; Store color at (6,3)
LD R6, [R4, #6]    ; Get row 6 base address
ST R5, [R6, #4]    ; Store color at (6,4)

; --- Yellow-ish (0x00F6) - 18 pixels ---
LD R5, [R4, #10]    ; Load color value
LD R6, [R4, #2]    ; Get row 2 base address
ST R5, [R6, #1]    ; Store color at (2,1)
LD R6, [R4, #2]    ; Get row 2 base address
ST R5, [R6, #2]    ; Store color at (2,2)
LD R6, [R4, #2]    ; Get row 2 base address
ST R5, [R6, #3]    ; Store color at (2,3)
LD R6, [R4, #2]    ; Get row 2 base address
ST R5, [R6, #4]    ; Store color at (2,4)
LD R6, [R4, #2]    ; Get row 2 base address
ST R5, [R6, #5]    ; Store color at (2,5)
LD R6, [R4, #2]    ; Get row 2 base address
ST R5, [R6, #6]    ; Store color at (2,6)
LD R6, [R4, #3]    ; Get row 3 base address
ST R5, [R6, #3]    ; Store color at (3,3)
LD R6, [R4, #3]    ; Get row 3 base address
ST R5, [R6, #4]    ; Store color at (3,4)
LD R6, [R4, #4]    ; Get row 4 base address
ST R5, [R6, #1]    ; Store color at (4,1)
LD R6, [R4, #4]    ; Get row 4 base address
ST R5, [R6, #2]    ; Store color at (4,2)
LD R6, [R4, #4]    ; Get row 4 base address
ST R5, [R6, #3]    ; Store color at (4,3)
LD R6, [R4, #4]    ; Get row 4 base address
ST R5, [R6, #4]    ; Store color at (4,4)
LD R6, [R4, #4]    ; Get row 4 base address
ST R5, [R6, #5]    ; Store color at (4,5)
LD R6, [R4, #4]    ; Get row 4 base address
ST R5, [R6, #6]    ; Store color at (4,6)
LD R6, [R4, #5]    ; Get row 5 base address
ST R5, [R6, #2]    ; Store color at (5,2)
LD R6, [R4, #5]    ; Get row 5 base address
ST R5, [R6, #5]    ; Store color at (5,5)
LD R6, [R4, #6]    ; Get row 6 base address
ST R5, [R6, #2]    ; Store color at (6,2)
LD R6, [R4, #6]    ; Get row 6 base address
ST R5, [R6, #5]    ; Store color at (6,5)

; --- White (0x00FF) - 40 pixels ---
LD R5, [R4, #11]    ; Load color value
LD R6, [R4, #0]    ; Get row 0 base address
ST R5, [R6, #0]    ; Store color at (0,0)
LD R6, [R4, #0]    ; Get row 0 base address
ST R5, [R6, #1]    ; Store color at (0,1)
LD R6, [R4, #0]    ; Get row 0 base address
ST R5, [R6, #2]    ; Store color at (0,2)
LD R6, [R4, #0]    ; Get row 0 base address
ST R5, [R6, #3]    ; Store color at (0,3)
LD R6, [R4, #0]    ; Get row 0 base address
ST R5, [R6, #4]    ; Store color at (0,4)
LD R6, [R4, #0]    ; Get row 0 base address
ST R5, [R6, #5]    ; Store color at (0,5)
LD R6, [R4, #0]    ; Get row 0 base address
ST R5, [R6, #6]    ; Store color at (0,6)
LD R6, [R4, #0]    ; Get row 0 base address
ST R5, [R6, #7]    ; Store color at (0,7)
LD R6, [R4, #1]    ; Get row 1 base address
ST R5, [R6, #0]    ; Store color at (1,0)
LD R6, [R4, #1]    ; Get row 1 base address
ST R5, [R6, #1]    ; Store color at (1,1)
LD R6, [R4, #1]    ; Get row 1 base address
ST R5, [R6, #2]    ; Store color at (1,2)
LD R6, [R4, #1]    ; Get row 1 base address
ST R5, [R6, #3]    ; Store color at (1,3)
LD R6, [R4, #1]    ; Get row 1 base address
ST R5, [R6, #4]    ; Store color at (1,4)
LD R6, [R4, #1]    ; Get row 1 base address
ST R5, [R6, #5]    ; Store color at (1,5)
LD R6, [R4, #1]    ; Get row 1 base address
ST R5, [R6, #6]    ; Store color at (1,6)
LD R6, [R4, #1]    ; Get row 1 base address
ST R5, [R6, #7]    ; Store color at (1,7)
LD R6, [R4, #2]    ; Get row 2 base address
ST R5, [R6, #0]    ; Store color at (2,0)
LD R6, [R4, #2]    ; Get row 2 base address
ST R5, [R6, #7]    ; Store color at (2,7)
LD R6, [R4, #3]    ; Get row 3 base address
ST R5, [R6, #0]    ; Store color at (3,0)
LD R6, [R4, #3]    ; Get row 3 base address
ST R5, [R6, #2]    ; Store color at (3,2)
LD R6, [R4, #3]    ; Get row 3 base address
ST R5, [R6, #5]    ; Store color at (3,5)
LD R6, [R4, #3]    ; Get row 3 base address
ST R5, [R6, #7]    ; Store color at (3,7)
LD R6, [R4, #4]    ; Get row 4 base address
ST R5, [R6, #0]    ; Store color at (4,0)
LD R6, [R4, #4]    ; Get row 4 base address
ST R5, [R6, #7]    ; Store color at (4,7)
LD R6, [R4, #5]    ; Get row 5 base address
ST R5, [R6, #0]    ; Store color at (5,0)
LD R6, [R4, #5]    ; Get row 5 base address
ST R5, [R6, #1]    ; Store color at (5,1)
LD R6, [R4, #5]    ; Get row 5 base address
ST R5, [R6, #6]    ; Store color at (5,6)
LD R6, [R4, #5]    ; Get row 5 base address
ST R5, [R6, #7]    ; Store color at (5,7)
LD R6, [R4, #6]    ; Get row 6 base address
ST R5, [R6, #0]    ; Store color at (6,0)
LD R6, [R4, #6]    ; Get row 6 base address
ST R5, [R6, #1]    ; Store color at (6,1)
LD R6, [R4, #6]    ; Get row 6 base address
ST R5, [R6, #6]    ; Store color at (6,6)
LD R6, [R4, #6]    ; Get row 6 base address
ST R5, [R6, #7]    ; Store color at (6,7)
LD R6, [R4, #7]    ; Get row 7 base address
ST R5, [R6, #0]    ; Store color at (7,0)
LD R6, [R4, #7]    ; Get row 7 base address
ST R5, [R6, #1]    ; Store color at (7,1)
LD R6, [R4, #7]    ; Get row 7 base address
ST R5, [R6, #2]    ; Store color at (7,2)
LD R6, [R4, #7]    ; Get row 7 base address
ST R5, [R6, #3]    ; Store color at (7,3)
LD R6, [R4, #7]    ; Get row 7 base address
ST R5, [R6, #4]    ; Store color at (7,4)
LD R6, [R4, #7]    ; Get row 7 base address
ST R5, [R6, #5]    ; Store color at (7,5)
LD R6, [R4, #7]    ; Get row 7 base address
ST R5, [R6, #6]    ; Store color at (7,6)
LD R6, [R4, #7]    ; Get row 7 base address
ST R5, [R6, #7]    ; Store color at (7,7)

END_PROGRAM
B END_PROGRAM    ; Infinite loop